### ISSUE TITLE
Share or Download Posters

### ISSUE THREAD

**Issue by LeandroPelegrini** [ErfanRht/MovieLab#14]
When watching movies, I really like to share posters, is It possible to add this feature?

Click on a poster just do nothing, It will be nice to expand and add a Button to share or download It.

Similar to what MovieBase does, thanks and great app!

**Comment by ErfanRht** [comment]
That's a great idea!
I will work on it asap :)

**Comment by ErfanRht** [comment]
It's been fixed in [2.0.6](https://github.com/ErfanRht/MovieLab/releases/tag/v2.0.6). Check it out!
