### ISSUE TITLE
Version issue

### ISSUE THREAD

**Issue by Kreuger** [ErfanRht/MovieLab#25]
Hey. I had 1.0.6 installed from FDroid. I downloaded 2.0.6 from here and when I opened the apk in App Manager, it showed the app as a downgrade and not an upgrade. I decided to try removing it and installing the new version after. Immediately I got a notification of a new version but it says 1.0.6. Whats going on here?

**Comment by ErfanRht** [comment]
Hi, Thanks for pointing that out.
Can you please send me the app page in FDroid, 'cause I haven't applied the app in there and I couldn't found the app page in FDroid either

**Comment by Kreuger** [comment]
Its in the [IzzyOnDroid](https://apt.izzysoft.de/fdroid/index/apk/com.example.movielab) repo.

**Comment by Kreuger** [comment]
I just downloaded the 3.0.1 release off this page and it still shows 2.0.6. 

Edit: Uninstalling and installing again fixed it.
