### ISSUE TITLE
"See list" button displayed after adding movies to watchlist doesn't work

### ISSUE THREAD

**Issue by jotbeh** [ErfanRht/MovieLab#26]
After adding a movie to your watchlist, a confirmation bubble is shown. It has a "see list" button, which does not work when clicked.

https://user-images.githubusercontent.com/27549997/188266108-d379bd04-eabd-4a87-8221-0d66cb502a52.mp4

**Comment by ErfanRht** [comment]
Thanks for pointing that out.
I wasn't aware of that, will fix it asap.
